<?php

/**
 * BaseSkinnyList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $private
 * @property Doctrine_Collection $items
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method boolean             getPrivate() Returns the current record's "private" value
 * @method Doctrine_Collection getItems()   Returns the current record's "items" collection
 * @method SkinnyList          setName()    Sets the current record's "name" value
 * @method SkinnyList          setPrivate() Sets the current record's "private" value
 * @method SkinnyList          setItems()   Sets the current record's "items" collection
 * 
 * @package    skinny
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseSkinnyList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skinny_list');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('private', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SkinnyItem as items', array(
             'local' => 'id',
             'foreign' => 'list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}