<?php

/**
 * BaseSkinnyItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $text
 * @property integer $list_id
 * @property SkinnyList $SkinnyList
 * 
 * @method string     getName()       Returns the current record's "name" value
 * @method string     getText()       Returns the current record's "text" value
 * @method integer    getListId()     Returns the current record's "list_id" value
 * @method SkinnyList getSkinnyList() Returns the current record's "SkinnyList" value
 * @method SkinnyItem setName()       Sets the current record's "name" value
 * @method SkinnyItem setText()       Sets the current record's "text" value
 * @method SkinnyItem setListId()     Sets the current record's "list_id" value
 * @method SkinnyItem setSkinnyList() Sets the current record's "SkinnyList" value
 * 
 * @package    skinny
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseSkinnyItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skinny_item');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('text', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('list_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SkinnyList', array(
             'local' => 'list_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}