<?php

/**
 * SkinnyItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    skinny
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class SkinnyItem extends BaseSkinnyItem
{
  /**
   * Returns the html version of the content
   */

  public function getContentHtml()
  {
    require_once(sfConfig::get('sf_lib_dir').'/vendor/markdown.php');
    return Markdown(htmlspecialchars($this->text));
  }

}
