<?php

/**
 * SkinnyList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    skinny
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class SkinnyList extends BaseSkinnyList
{
  public function isOwner($user = null)
  {
    if (!isset($user) || !$user->getGuardUser()){
      return false;
    }
    return ($this->getUserId() == $user->getGuardUser()->getId()) ? true : false;
  }
  public function getShortDescription($length){
    return (substr($this->description, 0, $length));
  }
  public function getDescriptionHtml(){
    require_once(sfConfig::get('sf_lib_dir').'/vendor/markdown.php');
    return Markdown(htmlspecialchars($this->description));
  }
}
